# TensorFlow Fundamentals Extra-curriculum

In [1]:
import tensorflow as tf

In [2]:
minst = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = minst.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0

In [3]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

# Building a machine learning model

In [4]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(X_train[:1]).numpy()
predictions

array([[-0.09921435, -0.03838586,  0.21896097, -0.11241025,  0.2091459 ,
        -0.11129639,  0.09896585, -0.696967  , -0.04697626,  0.80599   ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.08285897, 0.0880556 , 0.11389937, 0.08177276, 0.11278692,
        0.08186389, 0.10102017, 0.04557628, 0.08730241, 0.2048636 ]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.5026972

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3022 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1479 - accuracy: 0.9557
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1113 - accuracy: 0.9665
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0910 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0787 - accuracy: 0.9759


In [12]:
model.evaluate(X_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0737 - accuracy: 0.9775 - 901ms/epoch - 3ms/step


[0.07367762178182602, 0.9775000214576721]

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [15]:
probability_model(X_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.12368032e-08, 5.89867843e-09, 9.93826598e-06, 3.32095602e-04,
        5.64038469e-11, 2.08784442e-07, 7.22210445e-15, 9.99657035e-01,
        1.00595003e-07, 4.89636477e-07],
       [2.24657235e-08, 2.91865988e-04, 9.99705970e-01, 1.85977262e-06,
        2.43035617e-16, 1.36286658e-07, 6.44418208e-08, 1.80324082e-12,
        5.71040193e-09, 4.84800207e-16],
       [1.07747121e-06, 9.99609649e-01, 6.60552905e-05, 1.02946706e-05,
        9.86460691e-06, 8.30688975e-07, 2.56518324e-05, 1.84586490e-04,
        9.10745293e-05, 1.07198787e-06],
       [9.99873042e-01, 1.16582344e-08, 1.11967165e-05, 1.62100875e-07,
        9.04655124e-08, 9.11805273e-06, 1.03532897e-04, 1.64324092e-06,
        4.42809078e-09, 1.07026074e-06],
       [2.07487960e-06, 7.49181073e-09, 3.58161401e-07, 1.25317072e-07,
        9.98538256e-01, 8.58767066e-08, 3.44436194e-05, 4.86780445e-05,
        5.06371180e-06, 1.37092348e-03]], dtype=float32)>