#### Neural Network Regression with TensorFlow

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

In [5]:
X, y = make_regression(n_samples=10000, n_features=50, n_informative=30,noise=0.7)

In [6]:
X[:5]

array([[-0.51438075, -0.23113387,  0.65580451, -0.62152889,  0.77361985,
         1.19406007, -0.71401346, -0.63280107, -0.08549832, -0.40664865,
         0.5822853 , -0.16124928, -0.74014077, -0.52410781,  1.45826776,
         0.86035429, -0.5399465 , -0.76592893,  1.07074445,  0.04178777,
         0.32756218,  0.64360272,  0.08456866,  1.73796461,  0.25487326,
        -1.63178313,  0.53907527,  0.07895046, -1.00508884, -0.06214507,
        -0.20757306,  1.60189738, -1.89897807, -1.24764655, -1.1662605 ,
        -1.22622689,  0.17112392,  0.33879022,  0.95441592,  2.50320246,
         1.13778112, -1.2005709 , -1.21794931,  0.87024935, -1.30294165,
        -0.16531908, -2.0793547 , -0.50942747,  0.13724961, -0.80817195],
       [ 0.0767694 , -1.04550526,  1.41297352,  0.01819008,  0.19143866,
         1.11868206, -0.3575357 ,  0.07079856,  1.38448139,  0.76876156,
         0.8953198 ,  0.11637117, -0.21083618, -0.45079203, -0.13745562,
         0.47764345, -0.23333334,  0.66918109, -0.

In [7]:
y[:5]

array([ -84.09335673,    7.00991213,  137.85660778,  149.07586059,
       -365.67879205])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
(X_train.shape, y_train.shape), (X_test.shape, y_test.shape)

(((8000, 50), (8000,)), ((2000, 50), (2000,)))

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [11]:
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [12]:
y_pred

array([-480.6270218 ,    6.23984107,  751.60777085, ..., -276.79268512,
        500.17650641,  118.46356716])

In [13]:
model.coef_, model.intercept_, model.n_features_in_

(array([ 5.47241878e+01,  3.84480715e+01,  1.29240212e+01,  2.50848845e+01,
         9.28718071e+01,  8.30680906e-04, -8.08994709e-04,  6.10801522e+01,
         5.26033639e+01,  1.23123855e+00,  9.53751996e+01,  3.98014818e+01,
         9.03865700e+01, -1.68686553e-02,  1.13501230e-02,  6.23636485e-03,
        -1.62018981e-03, -1.23329644e-02,  1.58866108e+01,  8.40872453e+01,
         2.78059262e-03,  5.17797630e+01, -5.49132310e-03,  1.07233665e-02,
         9.79363874e+01, -3.45234830e-03,  1.08687822e-02,  9.23943676e+01,
         1.31776098e+00,  1.06007160e+01,  7.54129248e+01, -6.10125929e-03,
        -2.02200457e-03, -3.77604499e-03,  1.06213456e+01,  7.46431627e-03,
         4.76398557e-03,  6.01239723e+01,  8.17381571e+01,  7.90919184e+01,
         5.03583815e-03,  5.74445060e+01,  2.41865205e+01,  2.27641245e-03,
         6.72911382e+01,  8.13303999e-03,  8.83916157e+01,  5.58788451e+00,
         2.17701099e+01,  4.05639744e+01]),
 -0.005929600066027607,
 50)

In [14]:
mae = mean_absolute_error(y_test, y_pred)
mae

0.561498304718784

In [15]:
model.score(X_test, y_test)

0.9999950725031818

In [16]:
from matplotlib import pyplot as plt

In [19]:
tf.random.set_seed(42)

tensor_X_train = tf.constant(X_train)
tensor_X_test = tf.constant(X_test)
tensor_y_train = tf.constant(y_train)
tensor_y_test = tf.constant(y_test)

model_nn = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

model_nn.compile(loss=tf.keras.losses.mean_absolute_error,
                 optimizer=tf.keras.optimizers.Adam(),
                 metrics=["mae"])

model_nn.fit(tensor_X_train, tensor_y_train, epochs=50)

Epoch 1/50
250/250 [==============================] - 4s 6ms/step - loss: 261.1961 - mae: 261.1961
Epoch 2/50
250/250 [==============================] - 2s 6ms/step - loss: 254.2050 - mae: 254.2050
Epoch 3/50
250/250 [==============================] - 1s 6ms/step - loss: 239.1964 - mae: 239.1964
Epoch 4/50
250/250 [==============================] - 2s 7ms/step - loss: 216.7298 - mae: 216.7298
Epoch 5/50
250/250 [==============================] - 2s 7ms/step - loss: 187.7547 - mae: 187.7547
Epoch 6/50
250/250 [==============================] - 2s 9ms/step - loss: 153.0790 - mae: 153.0790
Epoch 7/50
250/250 [==============================] - 2s 9ms/step - loss: 113.6072 - mae: 113.6072
Epoch 8/50
250/250 [==============================] - 3s 10ms/step - loss: 70.8328 - mae: 70.8328
Epoch 9/50
250/250 [==============================] - 3s 13ms/step - loss: 28.2987 - mae: 28.2987
Epoch 10/50
250/250 [==============================] - 5s 18ms/step - loss: 2.2198 - mae: 2.2198
Epoch 11/50
25

In [20]:
score = model_nn.evaluate(tensor_X_test, tensor_y_test)

print("Test loss:", score[0])
print("Test accuracy:", score[1])

63/63 [==============================] - 4s 19ms/step - loss: 0.6573 - mae: 0.6573
Test loss: 0.6572561860084534
Test accuracy: 0.6572561860084534
